[package]
name = "advanced_code_generator_chatbot"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tonic = "0.8"
prost = "0.11"

[build-dependencies]
tonic-build = "0.8"
